USE GANESHA;
CREATE TABLE DEPT (DEPTNO INT,DNAME VARCHAR(15),LOC VARCHAR(10));
INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK'),(20, 'RESEARCH', 'DALLAS'),(30, 'SALES', 'CHICAGO'),(40, 'OPERATIONS', 'BOSTON');
SELECT * FROM DEPT;